### PR TITLE
(doc) Fix markdown headings

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
This will allow them to render correctly on the site, as they currently aren't:

image

**Comment by bcurran3** [comment]
This is actually a global problem with all my packages over the last year or two.
Weird how poundpoundword displays correctly in marker, but not on chocolatey.org or two online markdown editors I checked out.
My template has been updated.
My packages will have to be updated individually as time moves forward.
No need for the pull request, and I don't merge back anyways. So I'm going to just close this. Thanks for figuring out the problem.

**Comment by gep13** [comment]
> No need for the pull request, and I don't merge back anyways.

Genuine question... can I ask why not?

**Comment by bcurran3** [comment]
out of sync

**Pull request closed without merging**
