### PR TITLE
PR to remove uTorrent in favor of hosting it in the core-team repository

### PR DESCRIPTION
**Pull request by The-Running-Dev**

### CODE REVIEW

**Comment by bcurran3** [comment]
Boyan,

I'm still confused about the ramifications of this.

I see the merge pull request, but don't see any changes.

Does accepting delete it from my account and move it to the core? 

What is the difference from it being in the core-team repository from the normal repository? 

What are the qualifications for a package becoming part of core?

Chocolatey team will now do updates?

Am I losing maintainership?

If not, how do I go about updating it in the future? Any extra steps I have to do or just update and push as normal?

You mentioned you had an update script working - looking back you didn't say you were going to send it to me, but I was running under that impression before as I want to start setting up my packages for auto-updates and could use the examples/help.

**Comment by bcurran3** [comment]
Hello?

**Comment by The-Running-Dev** [comment]
I'm sorry for the late reply bud.

You merging the pull requests removes it from your repository, you don't
have to do anything more. That is what they want me to do in order to move
it to the core team repo.

You don't have to do anything going forward. Once I finish the PR for the
core-team-repo and they merge it, the package has an update script that
will run every 6 hours (as most packages in the core-team-repo) and that
will create new versions of the package as the software gets updated.

Does that answer your questions?

**Comment by AdmiringWorm** [comment]
Let me see if I can't answer your questiones (step by step).

> Does accepting delete it from my account and move it to the core?

No it doesn't, you'll still be listed as the maintainer of the utorrent package, but the chocolatey user will also be listed as the maintainer (only from this repository).

> What is the difference from it being in the core-team repository from the normal repository?

There are two main differences IMO.
1. Being in the core team repository makes it available for several maintainers to work on it, as well as I believe more users are aware of the repository. Both of those points make it more likely that if an issue occurs it may be dealt with sooner.
2. The chocolatey user is trusted, which means all packages submitted by the chocolatey user will be automatically approved.

*There are other differences, but can't for the life of me remember them right now.

> What are the qualifications for a package becoming part of core?

There is no set hard rules for a package to become a part of the core-team packages repo, other than a package is following our [contribution guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)

> Chocolatey team will now do updates?

Yes, while you're the main maintainer that is meant to provide updates when a package is failing. The core team packages team will also provide updates, as well as it's (as @The-Running-Dev said) updated every sixth hour using AU.

> Am I losing maintainership?

No, you do not.

> If not, how do I go about updating it in the future? Any extra steps I have to do or just update and push as normal?

You can update and push the package as normal, it is highly prefered that changes is done through a PR to the core team repository though, this can be after the package have been pushed of course.

> You mentioned you had an update script working - looking back you didn't say you were going to send it to me, but I was running under that impression before as I want to start setting up my packages for auto-updates and could use the examples/help.

The update script @The-Running-Dev is talking about is the update script needed for updating a package through AU, which is currently available here:
https://github.com/The-Running-Dev/Chocolatey-CoreTeamPackages/blob/3ce4fab5e9701018cc47a325ee5e9fd23f94b6fc/automatic/utorrent/update.ps1

**Comment by bcurran3** [comment]
Thanks Kim, that explains it all much better.

**Comment by AdmiringWorm** [comment]
No problem, if you got any more questions and/or concerns, please don't hesitate to reach out to us on our gitter channel.
https://gitter.im/chocolatey/chocolatey-coreteampackages

**Pull request merged**
