### PR TITLE
Update FortiClient version to 7.0.1

### PR DESCRIPTION
**Pull request by BJD1997**
Tested the package locally and succesfully installs FortiClient 7.0.1
Hope the package can be updated this way to a somewhat more recent version :)

### CODE REVIEW

**Comment by bcurran3** [comment]
Hey BJ! Looks like you "cracked the code." Congrats.

I'm happy to merge this in and push out an update as a bunch of people want it, but before I do... wouldn't you like to be a maintainer? Then you can do it. :-) 

My FortiGate F80E is has been collecting dust for a year or two and I don't have any active clients using FGs at the moment. Let me pass this on to you.

**Comment by BJD1997** [comment]
I would like to but i'm not sure I can crack the code (yet) on the online installer (versions past 7.0.1)
How do I become the new maintainer for this package?

**Comment by bcurran3** [comment]
Just let me know your Chocolatey ID

**Comment by BJD1997** [comment]
https://community.chocolatey.org/profiles/BJD1997
Created a Profile on the community. Is this what you need? If not where do I get my Chocolatey ID?

**Comment by bcurran3** [comment]
BJD1997 - that's it. You should get an e-mail now inviting you to become a maintainer.

**Comment by BJD1997** [comment]
Yes I see myself as maintainer now on Chocolatey. And have replicated the package on my own respository.
https://github.com/BJD1997/ChocolateyPackages. 

Can I publish the fix to my repo directly or should I change the resource url first?
Also do you still want yourself to be listed as maintainer? If not I can remove your user from the package if you want.

**Comment by bcurran3** [comment]
You should update the package metadata appropriately
You should push the update.
You should leave the maintainer list alone.

I'm going to go ahead and close this as you've now got the ability to update the package now.

**Pull request closed without merging**
