### PR TITLE
Upgrade SetACL from 3.0.6 to 3.1.2 fixing #309

### LINKED ISSUE #309: Any plans to upgrade SetACL to the new version?
[SetACL 3.1.2](https://helgeklein.com/download/) has been available for quite a while now.

Any plans to upgrade to it from the current 3.0.6?

Are you open for pull request (since there are a few open ones)?

### PR DESCRIPTION
**Pull request by jpluimers**
Updates .nuspec (version) and install script (download URL and sha256)

fixes #309

### CODE REVIEW

**Comment by aetonsi** [comment]
Hi @bcurran3, any timeline about the possible merging of this? And thanks @jpluimers, hope you're doing well

**Comment by bcurran3** [comment]
Repo is finally sync fixed!

Not sure why choco-cleaner files are mixed in with this... possibly from "fixing" the repo?

If this is still current and you pull out the CC stuff, I'll probably pull it in this weekend. Sorry for the delay.

**Comment by aetonsi** [comment]
> If this is still current 

v3.1.2 is still the latest version if that's what you're asking

**Comment by bcurran3** [comment]
Can you pull the choco-cleaner stuff from the PR please? I tried, not sure I did it right.

**Review by bcurran3 — CHANGES_REQUESTED** [review]
Please remove choco-cleaner/tools/choco-cleaner.ps1 from the PR

**Comment by bcurran3** [comment]
Ironically I updated the package back in Oct 2022 but never pushed it.

nuspec needed more updating to fix markdown issues, add release notes and other things.
install script needed more updating as there are 32bit and 64bit versions of the program and shimgen would make a shim for each; first overwriting the 2nd. So if you're on a 32bit machine the shim wouldn't work since it was pointing to the 64bit version. I now autogenerate an .ignore file for the non-appropriate file during install.

Pushed new version.
choco install setacl --version=3.1.2.86

**Comment by aetonsi** [comment]
Hi, just out of curiosity, how long does it take for chocolatey to make a new version (3.1.2 in this case) the "main" one?
Or will it always be necessary to specify `--version=xxx` to upgrade?

**Comment by bcurran3** [comment]
Until a package has been updated at least 3 times with no problems, it has to go through human moderation. That moderation can take a few days to a month depending on how big the queue is and the time availability of the volunteers that do it.

**Comment by aetonsi** [comment]
Oh ok i see, thanks for the info. Cool to know.

**Comment by jpluimers** [comment]
> Hi @bcurran3, any timeline about the possible merging of this? And thanks @jpluimers, hope you're doing well

Thanks. I'm still alive and doing OK. Will post an update to the original issue shortly.

**Pull request closed without merging**
