### PR TITLE
Used AutoHotkey to make installer unattended

### PR DESCRIPTION
**Pull request by pauby**
I used AutoHotkey to make the installer unattended but it's still visible on teh screen. Logitech, in their infinite wisdom, have decided to code up their own installer which is a PITA to automate. It also stays on screen during the installation process. I automated what I could.

The only button that may pop up is the firewall button to ask if you want to allow the software to communicate externally. The end user will have to decidde this for themself. However there is a 'share data with Logtech' button in the ionstaller which I automate clicking no to.

I added AutoHotkey as a dependency in the nuspec and I rewrote the chocolateyInstall (mainly just because I use a template and it made my life easier).

Let me know if it's useful - it does work. But it's not ideal.

### CODE REVIEW

**Comment by pauby** [comment]
Bump.

**Comment by bcurran3** [comment]
Just saw this last night. I'll test and then most likely move forward.

**Comment by pauby** [comment]
Bump. If you're not going to use this PR can you let me know as I need to make alternative arrangements to get my system updated.

Cheers,

**Comment by bcurran3** [comment]
git installed locally now - I'm modernizing.

**Pull request closed without merging**
