### PR TITLE
 v11.1.5.16724464 - ADDLOCAL=ALL

### PR DESCRIPTION
**Pull request by virtualex-itv**
Added the `ADDLOCAL=ALL` parameter to do a Complete Install of VMware Tools

### CODE REVIEW

**Comment by bcurran3** [comment]
What components don't install by default that you want to install via this?

REF: https://docs.vmware.com/en/VMware-vSphere/5.5/com.vmware.vmtools.install.doc/GUID-E45C572D-6448-410F-BFA2-F729F2CDA8AC.html

**Comment by bcurran3** [comment]
@virtualex-itv You're usually a fast responder. Hope you're OK. Or if you don't have an answer, please say so.

**Comment by virtualex-itv** [comment]
hey @bcurran3 -  sorry I didn't see this sooner.  A lot our newer VMware solutions are now taking advantage of capabilities which are being added directly into VMware Tools as a way to remain "agentless" so this requires that the complete install of VMware Tools be performed rather than the "typical" install.  Internally, it's recommended best practice to do a complete install of Tools.  If you'd rather not add this parameter as the default install method, maybe adding it as an optional parameter would be a good idea then so it can be installed via something like `choco install vmware-tools --params "ADDLOCAL=ALL"`

**Comment by bcurran3** [comment]
I'm not against it, I'd just like to know what the difference is. i.e. What is missing from a typical install versus a full install?

(I'm actually pro full install of everything since it prevents gotchas down the line.)

**Comment by virtualex-itv** [comment]
Typical installs the basic drivers:
Audio, mouse, SVGA, VMXNET, MemCtl, etc.

The complete install adds following drivers/modules:
PVSCSI, VMXNET3, FileIntrospection (NSX), NetworkIntrospection (NSX), AppDefense, etc. 

Just to name a few... :)

I was thinking maybe you could do the `ADDLOCAL=ALL` as the default install, and then add additional parameter(s) to remove specific modules one does not want/need them installed `choco install vmware-tools --param "REMOVE=AppDefense"` as an example.

Here's a list of the current set up modules: https://docs.vmware.com/en/VMware-Tools/11.1.0/com.vmware.vsphere.vmwaretools.doc/GUID-E45C572D-6448-410F-BFA2-F729F2CDA8AC.html#

**Comment by virtualex-itv** [comment]
@bcurran3 - hey bud, any update on this?

**Comment by bcurran3** [comment]
Under consideration and in need of research to find out what the difference is.

1 - From experience I know PVSCSI and VMXNET3 are installed by default and don't need ALL.
2 - I'm in belief of whatever the difference is between default and all, if VmWare wanted everything installed by default it would default that way. 
3 - no one else has asked for this but you
4 - I'd like to know any real advantages and see the published delta info as well as the disk space diff

I think this is better handled via Chocolatey's --install-arguments option for the edge cases.

**Comment by virtualex-itv** [comment]
Fair enough...I'm in agreement that a better option would be to add it as a parameter.  I can look into updating this and resubmitting a PR unless you want to take care of it all.  Let me know...

**Comment by bcurran3** [comment]
If you want to update it as an optional package parameter, I'm all for it.

**Comment by virtualex-itv** [comment]
ok I will work on that then and  submit a new PR.  will you also consider adding me as a co-maintainer?  I obviously wouldn't make any "changes" without running by you first.  I think we make a good team!

**Comment by virtualex-itv** [comment]
param configured, tested, and working @bcurran3 - will close this PR and resubmit.

**Pull request closed without merging**
