### PR TITLE
Update speedtest icon

### PR DESCRIPTION
**Pull request by xmha97**

### CODE REVIEW

**Review by bcurran3 — COMMENTED** [review]
Hi. Thanks. 
Can't use GH raw links though; should be a CDN link.

**Comment by xmha97** [comment]
> 
> 
> Hi. Thanks.
> Can't use GH raw links though; should be a CDN link.

Fixed.

**Review by bcurran3 — COMMENTED** [review]
Thanks. I hate to be picky but that one is inverse of the one that I see. 

image

I'm not adverse to adding the jpg to the repo so that it can be static forever. Just a thought.

**Comment by xmha97** [comment]
> 
> 
> Thanks. I hate to be picky but that one is inverse of the one that I see.
> 
> image
> 
> I'm not adverse to adding the jpg to the repo so that it can be static forever. Just a thought.

OK, now I added Chrome web store official icon (128x128)

**Comment by bcurran3** [comment]
@xmha97 I'll pull this in as the icon seems good and stable months later. 
BUT there are unrelated files for go-contact-sync-mod added to the mix.

**Comment by TheCakeIsNaOH** [comment]
@bcurran3 @xmha97 this should not be merged as it currently is, this PR has the ~250 commits that were cleaned out because they had binaries.

Rebasing on the latest master would work as a fix, as would creating a fresh branch+pr and coping over the change manually. Or  @bcurran3 you could always copy over the change manually.

**Comment by bcurran3** [comment]
I manually did this via https://github.com/bcurran3/ChocolateyPackages/commit/d75955b4c235360a593119950b7c19533731da4c to get it knocked out and to avoid any problems.

Thanks for tracking that down @xmha97.

**Pull request closed without merging**
