### PR TITLE
(doc) Typo

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Review by bcurran3 — APPROVED** [review]
Thanks - updated on my local working copy as well.

**Comment by bcurran3** [comment]
I'm just going to close this as it's fixed for next release and I don't sync local and GitHub. (Might do in the future.)

**Comment by ferventcoder** [comment]
Lost on that statement bud

**Comment by bcurran3** [comment]
git installed locally now - I'm modernizing.

**Comment by gep13** [comment]
>@bcurran3 said...
git installed locally now - I'm modernizing.

Let me know if you have any questions 😄

**Pull request closed without merging**
