### PR TITLE
Fix AU script

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
Remove extra space at end of info file.
Move scripts directory to root of repository.
Adjust update.ps1 to point to it again.

### CODE REVIEW

**Review by bcurran3 — APPROVED** [review]
I haven't tested this, just going to trust it works...

**Comment by bcurran3** [comment]
Me thinky it good.

Thanks.

image

**Comment by bcurran3** [comment]
Now to understand the flow of what others do....

You manually run this when you think there might be an update? Or you schedule it to run automatically once a day/week/something?

Does this pack and push the package when run if a new version is found?

**Comment by TheCakeIsNaOH** [comment]
> You manually run this when you think there might be an update? Or you schedule it to run automatically once a day/week/something?

I will run it manually for developing/testing, and then it is a scheduled task, I run it once a day, the coreteam repository runs their  scripts every 6 hrs last I checked. Once you have multiple scripts, it is a lot to run them all, so there is are scripts here to help automate it: https://github.com/majkinetor/au-packages-template
The important files are `update_all.ps1` , `test_all.ps1`, `.appveyor.yml` , and the `update_vars_default.ps1` (rename to `update_vars.ps1` and fill in your passwords, and don't commit it) 

It is possible to run it on your local machine via a scheduled task, although that can fail if your computer is off, or your internet is down. Most people run it on Appveyor, which is free for open-source repositories and will enable scheduled runs upon request. See the wiki page on how to: https://github.com/majkinetor/au/wiki/AppVeyor

> Does this pack and push the package when run if a new version is found?

It will pack, it will not push as it currently is. See the above repository link for the `update_all.ps1` script that has an option to automatically push, if set in  `.appveyor.yml` / `update_vars.ps1` (depending on if run locally or in appveyor). I personally have appveyor set to push automatically, but running locally to not push because I am generally developing or fixing scripts, and I want to check that the package is working before I push it.

**Comment by bcurran3** [comment]
Thanks.

I guess I have a lot of reading to do which is why this has been pushed off so long (and will probably continue to do so).  :) i.e. AppVeyor - see lots of references to it but my level of knowledge currently is basically only that it exists and that it's another layer of learning.... all for  a hobby!

**Pull request merged**
