### PR TITLE
[choco-cleaner] Remove chocolatey cache and nuget cache for all users

### LINKED ISSUE #247: [choco-cleaner] not finding temp directory of ansible user
we use ansible to execute chocolatey via https://docs.ansible.com/ansible/2.6/modules/win_chocolatey_module.html

this executes with user sssansibleopsys

we've found a bunch of older files at C:\Users\sssansibleopsys\AppData\Local\Temp\chocolatey

but the scheduled run of choco cleaner doesn't seem to find them.  I didnt' see a config setting to turn detection of this location on, please advise?

### PR DESCRIPTION
**Pull request by crowebs**
fixes #247

### CODE REVIEW

**Comment by bcurran3** [comment]
Awesome. I've been meaning to do this for years. Soon as I have a chance I'll test and pull in.
(FYI: My repo is out of sync and because of this script - so it might be a bit for me to fix)

**Comment by crowebs** [comment]
I know you said it might be a while, but any feedback on this?

**Comment by bcurran3** [comment]
So I force-synced my repo last week or so.

Ironically I just did this today and came to GH because I remembered someone had mentioned it... I just had to move around a few lines I had done and commented long ago...and test. 

I'll have to compare and see if you did the same or something even better. I'll probably push  up what I did today later and then try to look at the diffs.

**Comment by bcurran3** [comment]
Pushed the updated package as a -pre for testing. 
choco install choco-cleaner --version=0.0.9.0-pre --pre

**Pull request closed without merging**
