### PR TITLE
PSScriptAnalyzer fixes

### PR DESCRIPTION
**Pull request by slycordinator**
Fixes to powershell scripts according to recommendations from PSScriptAnalyzer .

The changes are:
1) Replacing an alias for the full name
% -> ForEach-Object
? -> Where-Object
foreach -> ForEach-Object
select -> Select-Object
sort -> Sort-Object
start -> Start-Process
del -> Remove-Item
ChildItem -> Get-ChildItem
gwmi -> Get-WmiObject

2) Changing comparisons of a variable with $null to place $null on the left side
In PowerShell:
* $null -eq $var checks if $var is equal to $null; it makes it a boolean
* $var -eq $null searches through the elements of $var and returns a collection of those with a value equal to $null

### CODE REVIEW

**Comment by bcurran3** [comment]
This is neat.
Need to "digest."

**Comment by slycordinator** [comment]
Should be good now.

**Comment by bcurran3** [comment]
I'm really not a fan of it moving $null to the left of var checks, makes it harder (for me) to read. Is there an option you can give PSScriptAnalyzer  to not do that? If so, that would be my preference. If not, I guess I'll just have to deal with it. LMK.

**Comment by slycordinator** [comment]
Yes, you can disable any rule of PSScriptAnalyzer.

For instance, the cli utility Invoke-ScriptAnalyzer has an option
-ExcludeRule that takes a comma-separated string of each rule you wish to
exclude.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[Bella Ciao!](https://www.youtube.com/watch?v=9ao4FEaDGhQ)

**Pull request closed without merging**
