### PR TITLE
Cnc move args to params and add help comments

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
1. Moves all `$args -eq "item"` into the parameter block. 
This allows the removal of the explicit if blocks for setting up some of the variables. 
It also allows `Get-Help` to work properly. 
In the future, it could make more advanced things with options more easily implemented.
Also, it allows tab completion to work.

2. Removes references to `/?` as a switch to get to help. This has been broken since the `-path` parameter has been added, because if you currently run `CNC /?`  it will try run CNC at path `/?` since it is interpreted as the path to run CNC at. 

3. Adds a help comment so `Get-Help` works. I just mostly just copied and pasted, feel free to edit later. Once the structure is there, it is pretty simple to edit. 

4. Comments out the manual help output, and instead outputs `Get-Help -detailed`. It outputs the same info about the switches, and it means that only one place needs to be edited if the help information changes. 
I did not remove it completely so you can easily check what was there, and you can remove it at your convenience.

### CODE REVIEW

**Comment by bcurran3** [comment]
AWESOME!

I'll give it a whirl soon as I can. Looking forward to this "proper" change.

**Comment by bcurran3** [comment]
I'm anxious to add this but want to test first. I'll be damned if I can figure out how find a full copy of the modified script file. I looked at your repo and I don't see it. (Changes yes, but not the full file with the changes.) I'm not good enough with git to pull down the changes into some sort of test branch so I'm left clueless with how to test it. This is a general problem for me with using git for collaboration because I don't know how to test other people's work in a sandbox. I'm sure you know, enlighten me please.

**Comment by TheCakeIsNaOH** [comment]
There are a couple of ways you could go about getting the file.

1. Via files changed:
On this page, click the files changed tab. Then click the three dots on the right side, right below the review changes button, and hit view file in that pop up menu (see picture). Then you can hit the raw button and copy/paste.

This pop up menu:
image

2. Via branch in github
First, look at what branch I want to merge in, in this case it is `cnc-move-to-params`. See picture below. Then you can click it to open it directly, or you can go to my fork (https://github.com/TheCakeIsNaOH/ChocolateyPackages-1 ), and click the branch menu, and select the correct branch. See picture. Finally, navigate to the correct file.

Which branch:
image

Branch menu:
image

3. Via git clone and switch branch.
First, check which branch I am requesting to merge in, see option 2 for how.
Then clone my fork `git clone https://github.com/TheCakeIsNaOH/ChocolateyPackages-1.git ChocolateyPackage-naoh-fork`
Then switch to the correct branch `git checkout cnc-move-to-params`
Then navigate to `cnc.ps1` and open it.

4. Via git checkout of your current local copy.
Follow this guide: https://gist.github.com/piscisaureus/3342247
When you are done you can switch back to normal via `git checkout master`

5. Via GitHub CLI
Github cli: CD to your local copy of this repository and run `gh pr checkout 221`
When you are done, `git checkout master`

6. Via Github desktop
Click on the PR you want to see the changes from
image

**Comment by bcurran3** [comment]
I've been ignoring this until I have the time and mindset. When it takes lots of reading, multiple steps, and pictures.. it just seems so much easier to e-mail me the file. :)
(But I do want to LEARN it!)

**Comment by TheCakeIsNaOH** [comment]
Each numbered option is a different way. 

The easiest option is 1:
- Click the files changed tab on this PR
- Click the three dots right below the review changes button 
- Click the view file button. Should take you to this page: https://github.com/bcurran3/ChocolateyPackages/blob/cb649b7249d5a48d2523db4cd78b66932f6180bd/choco-nuspec-checker/tools/CNC.ps1
- Then either copy/paste, or click the raw button so you can do a crtl+a for easy selection to copy/paste.

**Comment by TheCakeIsNaOH** [comment]
@bcurran3 Any updates on getting this merged?

**Comment by bcurran3** [comment]
OK. I added my other little stuff and fixes to CNC. 

If you rebase, I can test and hopefully pull this in right away.

(I guess I'm kind of "back." LOL!)

**Comment by TheCakeIsNaOH** [comment]
Alright, I've rebased

**Comment by TheCakeIsNaOH** [comment]
@bcurran3 any update on getting this merged?

**Comment by bcurran3** [comment]
Says no conflicts...let's just do it and if there are any ramifications we'll deal with it later.

**Pull request merged**
