### PR TITLE
Add AU script to google-backup-and-sync

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
Check for updates by running the update.ps1 file.

This is not the most elegant AU script ever, but google does not publish a nice parsable changelog or anything.  

It needs the MSI module, and the AU module, as is to be expected. 
`Install-Module -Name MSI`
`cinst AU` or clone from the git

### CODE REVIEW

**Comment by bcurran3** [comment]
Thanks!
Ironic that I pushed a new version of this package 2-3 hours before this.
I'm going to test now and most likely approve.
I can probably use this as a base for many others.

**Comment by bcurran3** [comment]
On 2nd thought, I'm just going to merge it and update whatever I need to afterwards.

**Comment by TheCakeIsNaOH** [comment]
This is not the cleanest one, getting the version from the URL is probably ideal if the URL has the version,

For a nice clean AU script, look at this one.
https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/master/4k-video-downloader/update.ps1

If a program has both prerelease and stable versions, you can use a script like this
https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/master/nextcloud-client/update.ps1

It also downloads the binary to include in the package using `Get-RemoteFiles`

Also, if you have a tricky package to script, give me a ping, and I might be able to point you in the right direction.

**Comment by bcurran3** [comment]
UGH! 
I merged. I attempted to pull and then I got errors. I forced push and/or pull and didn't get any of these files. I just viewed raw and copied pasted into local files now.

Ran update and got:
image

Edited the extra period out of the scripts path and it runs, but
image

Edited nuspec to the version you were at, 3.51.3307.8076, and getting the same error trying to update.

image

> Also, if you have a tricky package to script, give me a ping, and I might be able to point you in the right direction.

Very much appreciated. Until I get one or two working and see the complete process flow to completion... They're ALL tricky!

**Comment by TheCakeIsNaOH** [comment]
Try completely closing the tab, and re-opening. AU does weird stuff sometimes with global variables.

**Comment by bcurran3** [comment]
Weird things are happening.

In a new Command Prompt followed by PowerShell: (run twice)
image

In new Terminal PowerShell session: (run twice)
image


....and I pushed my current files back up to GH if you want to view anything. (Only one character change from what you sent as far as I know.... maybe the info file is different.)

p.s. I had uninstalled AU months ago and did a fresh install right before this; and I did install the MSI module.

**Comment by TheCakeIsNaOH** [comment]
The scripts directory is not just for this one package, so it is supposed to be moved up one level to the root directory. Then add back the dot to `. "..\scripts\Update-OnETagChanged.ps1"`

**Comment by TheCakeIsNaOH** [comment]
See #197 

You can delete the info file and it will be recreated by the update script. Its purpose is to save the status of the link, so if the file at the link has not changed, it does not have to be downloaded and the version checked. So deleting it means that it will download the 32 bit msi to temp an extra time, so not a big deal in testing, but lots of extra time and bandwidth for day to day.

**Pull request merged**
