### PR TITLE
Update MAME to 0.218

### PR DESCRIPTION
**Pull request by unindented**

### CODE REVIEW

**Comment by bcurran3** [comment]
I just pushed .220

**Comment by bcurran3** [comment]
If you want to become maintainer, let me know!

**Comment by unindented** [comment]
I tried cloning the repo, but I had issues with file name casing (`chocolateyinstall.ps1` vs `ChocolateyInstall.ps1`). My OS would only see one of the two.

**Comment by bcurran3** [comment]
My repo is a mess. It shouldn't have the same file (well different versions) with the different case.
I'm probably going to have to delete it and replace it with the current versions and then go back to maintaining it.

**Comment by unindented** [comment]
If you get the repo to a good place where my OS doesn't get confused, I'd be happy to help keep a few packages up to date.

**Comment by bcurran3** [comment]
Appreciated. It's probably going to be a while. I don't currently use the repo at all and because of that end up aborting all PRs.

If you want to help maintain some packages, just shoot me a message with your Chocolatey ID and a list of packages and I'll add you as a maintainer. I'm going to be giving up a bunch of them that I don't use and don't have time to update any more.

**Pull request closed without merging**
