### PR TITLE
CNC add recurse

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
Related to #147 

Add a recurse switch to CNC. 
I did not indent the parts in the foreach loop, to reduce the changed lines. That can be done separately. 

Feel free to cherry-pick parts of this, or take inspiration if you do not want to merge directly.

### CODE REVIEW

**Review by bcurran3 — CHANGES_REQUESTED** [review]
Thanks!

I copied the complete file to test, but am getting errors.

Here's what happens for me:

image

image

**Comment by bcurran3** [comment]
I really wish I could make heads or tails of where the changes are!

**Comment by TheCakeIsNaOH** [comment]
Broad strokes, it wraps most of the script in a foreach loop. I moved a couple of the functions up out of the loop area, and moved the variables to inside the loop area so they get reset each loop.

See lines 742-751 for the start of the loop. https://github.com/bcurran3/ChocolateyPackages/pull/195/files#diff-6eedc1aeadcd5ac8d2b35a3738d516a3R742-R751

**Comment by bcurran3** [comment]
Does this work for you?
Any idea why it's failing for me? (I'm guessing just a missing quote.)
I just viewed the raw file again and saved it to a test, ran it and had the same problem.
Sorry to throw a mini-crowbar into the mix but I just pushed an update that ignores update.ps1 like you requested. :) I think it's only three line additions.

**Comment by TheCakeIsNaOH** [comment]
I just ran it on two dozen packages or so, no issues. 

You are pasting it into a UTF-8 BOM text file? 

Here is what I am using, pasting into notepad++, it is still working.
https://raw.githubusercontent.com/bcurran3/ChocolateyPackages/3d870f4665383c00474582bb6beb8a2f747a3743/choco-nuspec-checker/tools/CNC.ps1

**Comment by TheCakeIsNaOH** [comment]
I just rebased on your master, and git managed to merge it fine.

**Comment by bcurran3** [comment]
Great. Sorry for the hassle.

So I just viewed the raw file again, saved it locally as test.ps1, ran it and:
image

**Comment by bcurran3** [comment]
I'm editing the double quotes to single quotes and the error goes away.

Not sure why the double quotes worked before the changes but not after, but it's an easy enough fix and  better "style" anyway....

**Comment by TheCakeIsNaOH** [comment]
I have no clue either? At least there is a fix.

Feel free to edit it on your end, and push the results if that is easier.

**Comment by bcurran3** [comment]
Got stuck.

There are a few lines I can't use single quotes due to variable use.

The weird thing is I can copy and paste the same write-warning commands from the script into the CLI and there's no errors; as expected. Something in the modified script changes the behavior of <'s when found. Have to find the root cause of the behavioral change...

**Comment by TheCakeIsNaOH** [comment]
> There are a few lines I can't use single quotes due to variable use.

How about `Write-Host '< item>' + $variable + '<item>'`? Another hack.

**Comment by bcurran3** [comment]
Could work, but I just noticed the errors further down:

```
At S:\dev\GitHub\ChocolateyPackages\google-backup-and-sync\test.ps1:1403 char:79
+ ... if ($_ -match "\b(?:(?:https?|ftp|file)://|www\.|ftp\.)(?:\([-A-Z0-9+ ...
+                                                                  ~
Missing type name after '['.
At S:\dev\GitHub\ChocolateyPackages\google-backup-and-sync\test.ps1:1403 char:87
+ ... atch "\b(?:(?:https?|ftp|file)://|www\.|ftp\.)(?:\([-A-Z0-9+&@#/%=~_| ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At S:\dev\GitHub\ChocolateyPackages\google-backup-and-sync\test.ps1:1403 char:88
+ ... tch "\b(?:(?:https?|ftp|file)://|www\.|ftp\.)(?:\([-A-Z0-9+&@#/%=~_|$ ...
+                                                                 ~
Unrecognized token in source text.
At S:\dev\GitHub\ChocolateyPackages\google-backup-and-sync\test.ps1:1403 char:89
+ ... tch "\b(?:(?:https?|ftp|file)://|www\.|ftp\.)(?:\([-A-Z0-9+&@#/%=~_|$ ...
+                                                                  ~
Missing closing ')' in expression.
At S:\dev\GitHub\ChocolateyPackages\google-backup-and-sync\test.ps1:1404 char:45
+                    $urlsfound += $matches[0]
+                                             ~
Missing closing ')' in expression.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported
```

Hey, you never told me if you tested this change. :) 


FYI: Line numbers are probably off at this point...

**Comment by bcurran3** [comment]
I'd really like to have this work but I'm going to put it on hold until the changes are more legible/visable or I have time to work through it. :(

**Comment by TheCakeIsNaOH** [comment]
How about cloning my fork directly? 
https://github.com/TheCakeIsNaOH/ChocolateyPackages-1/tree/cnc-recurse-3

`git clone https://github.com/TheCakeIsNaOH/ChocolateyPackages-1.git`
`git checkout cnc-recurse-3`

I have seen zero of these issues on my end.

**Comment by bcurran3** [comment]
I did. Just did again. (https://raw.githubusercontent.com/TheCakeIsNaOH/ChocolateyPackages-1/cnc-recurse-3/choco-nuspec-checker/tools/CNC.ps1) Same problem.

But guess what? I previously saved w/o BOM. I just saved w/BOM and it's running through all my nuspecs now. Success. 

I have no clue why that makes a difference. Weird! The recommended saving for PowerShell files (on Windows and not cross-platform with Linux) is to save w/o BOM. 

I'd still like to see the changes and were they are though. 

Soon as I have time I'll see if I can do a diff between them and see if there's some statement I can add that will fix the BOM issue.

**Comment by bcurran3** [comment]
I think I'll add an if -recurse to log errors to a file.

**Comment by bcurran3** [comment]
Minor problem found - aborts recursion on a invalid nuspec file.

I'm guessing I've got a break in there that needs to be changed. Not looking into it now, just making note of it for the future.

image

**Comment by TheCakeIsNaOH** [comment]
> The recommended saving for PowerShell files (on Windows and not cross-platform with Linux) is to save w/o BOM.

I thought it was with BOM?
https://chocolatey.org/docs/create-packages#character-encoding

**Comment by bcurran3** [comment]
Geez I'm getting old and can barely remember my name. You're right, I got confused between nuspec and ps1. Doh! The world needs to make it's mind and just use or not use BOM with everything!

**Comment by bcurran3** [comment]
OK. I just went through it with a fine tooth comb (missing a few teeth) and I think I found all the changes, moved them into the version I updated yesterday and have it working.

I think I'll put up a -pre version with tomorrow's date to give you a chance to look at/test/give feedback/etc.

**Comment by bcurran3** [comment]
https://chocolatey.org/packages/choco-nuspec-checker/2020.09.21-pre

Please give it a spin. 

...and thanks again!

image

**Comment by TheCakeIsNaOH** [comment]
It is working for me, looks good.

**Comment by bcurran3** [comment]
Cool. Thanks again!

**Pull request closed without merging**
