### PR TITLE
(choco-package-list-backup) add support for saving arguments

### LINKED ISSUE #7: choco-package-list-backup: add used extra install arguments to the <package> nodes
please add any extra arguments (https://github.com/chocolatey/choco/wiki/CommandsInstall#packagesconfig) used during package installation when exporting

**example:**
```
choco feature enable -n=useRememberedArgumentsForUpgrades
choco install git --packageparameters "/GitOnlyOnPath /NoAutoCrLf /NoShellIntegration /NoGitLfs"
choco install tortoisegit --installarguments "ADDLOCAL=ALL REMOVE=MoreIcons,CrashReporter"
``` 

**expected packages.config:**
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
   <package id="git" packageParameters="/GitOnlyOnPath /NoAutoCrLf /NoShellIntegration /NoGitLfs" />
   <package id="tortoisegit" installArguments="ADDLOCAL=ALL REMOVE=MoreIcons,CrashReporter" />
</packages>
```

**actual packages.config:**
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
   <package id="git" />
   <package id="tortoisegit" />
</packages>
```

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
Fixes: #7

### CODE REVIEW

**Comment by bcurran3** [comment]
I want to pull this in.

I don't understand the reasoning behind the CDATA designation though.

Instead of
`        '<![CDATA[' + $args + ']]>'`
Why not just
`        '<SavedArgs="' + $args + '">'`

image

(^ Close.)

Either way I plan to pull it in and test. You're Write-PackagesConfig ForEach is much cleaner!

**Comment by TheCakeIsNaOH** [comment]
Alright, I just rebased this on the latest master, now that a fix for #233 is in master.

The reasoning for CDATA is that the arguments can have characters that are illegal for XML, (i.e. like <, > or &, and possibly more exotic things). The CDATA insulates that, so it just works and spits out valid xml. Basically think of it like single quotes.

https://en.wikipedia.org/wiki/CDATA

Another workaround is to do stuff like `&amp`, `&lt`, and `&gt`, but then you may have to encode and decode those, which is no fun. While with cdata you can just `get-content`, cast to XML, and go to town.

**Comment by bcurran3** [comment]
Do me a favor and do a choco install against a packages.config file generated by this and let me know what happens.

When I do it, I get:

```
PS C:\test> cinst .\packages.config
Chocolatey v0.10.15
Installing from config file:
.\packages.config
By installing you accept licenses for the packages.
Error deserializing response of type chocolatey.infrastructure.app.configuration.PackagesConfigFileSettings:
 There is an error in XML document (3, 48).
This is try 1/3. Retrying after 400 milliseconds.
 Error converted to warning:
 There is an error in XML document (3, 48).
Error deserializing response of type chocolatey.infrastructure.app.configuration.PackagesConfigFileSettings:
 There is an error in XML document (3, 48).
This is try 2/3. Retrying after 600 milliseconds.
 Error converted to warning:
 There is an error in XML document (3, 48).
Error deserializing response of type chocolatey.infrastructure.app.configuration.PackagesConfigFileSettings:
 There is an error in XML document (3, 48).
Maximum tries of 3 reached. Throwing error.

Chocolatey installed 0/0 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
There is an error in XML document (3, 48).
```

Which is the same problem I get when I use the SaveTitleSummary feature. choco.exe doesn't know how to handle this extra info in the file. Which makes the packages.config file nice to read, but unusable. I'm thinking both need to be added as a comment along with the normal package info.

Thoughts?

SIDE NOTE: install script needs to be updated to update the config file to add the new parameter. Just saying... if you continue to do the hard work, I'll through this in in 2-3 minutes. :)

EDIT: deserializing error might be missing /> (haven't investigated)

**Comment by bcurran3** [comment]
FOR REFERENCE:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
   <package id="7zip" title="7-Zip" arguments="<![CDATA[ --cache-location="'C:\Users\bcurran\AppData\Local\Temp\chocolatey'"]]>" />
  </packages>
```

**Comment by bcurran3** [comment]
Prepped for SaveArguments with https://github.com/bcurran3/ChocolateyPackages/commit/8ad04fcb55b85f7fad1907063d5610106a9d982c

**Comment by bcurran3** [comment]
A (working) mock up test for moving title and summary into comments:

```
Function Write-PackagesConfig{

        $body=choco list -lo -r -y | % { 
		'<!--' + "`ntitle: " + 
		(get-nuspecinfo "$($_.SubString(0, $_.IndexOf("|")))" "title") 
		"`nsummary: " + 
        (get-nuspecinfo "$($_.SubString(0, $_.IndexOf("|")))" "summary") + "`n"
		'-->' + "`n"
		"   <package id=`"$($_.SubString(0, $_.IndexOf("|")))`" />`n"
		}
		Write-Host $body

	   }
```

Gives results like this:

```
Choco Package List Backup Summary:
<!--
title: 7-Zip
summary: 7-Zip is a file archiver with a high compression ratio.
 -->
    <package id="7zip" />
 <!--
title: [Deprecated] 7-Zip (Portable, CommandLine)
summary: 7-Zip is a file archiver with a high compression ratio.
 -->
    <package id="7zip.commandline" />
 <!--
title: 7-Zip (Install)
summary: 7-Zip is a file archiver with a high compression ratio.
 -->
    <package id="7zip.install" />
 <!--
title: 7-Zip (Portable, CommandLine)
summary: 7-Zip is a file archiver with a high compression ratio.
 -->
    <package id="7zip.portable" />
```
This creates a very "busy" packages.config, but I kind of like it. 

Just fishing for comments. I was wondering if the SavedArguments might be good to put in the comments, but it'd be a bear to pull them out of the comments if I want to use the SavedArguments in something like InstChoco.

**Comment by TheCakeIsNaOH** [comment]
> Do me a favor and do a choco install against a packages.config file generated by this and let me know what happens.

I get the same thing you get.

Looking into cdata more, it might not work for this, it appears that the current syntax is not correct. Sigh. It looks like I'll get to do XML escaping.

>Which is the same problem I get when I use the SaveTitleSummary feature. choco.exe doesn't know how to handle this extra info in the file.

Hmm, could that be related to XML escaping as well? I'll play arround with this more.

> I'm thinking both need to be added as a comment along with the normal package info.

Since arguments can't be applied to individual packages anyway, I was counting on needing extra code to actually use these arguments. So I'm kind of ok with this.

**Comment by TheCakeIsNaOH** [comment]
Ok, I've rebased on your master branch to deal with the merge conflict.

**Comment by TheCakeIsNaOH** [comment]
Ah, I've found something. `[System.Security.SecurityElement]::Escape()` can be used to escape data for use with xml.

Check out the latest commit, it should be working now. You should be able to install a `packages.config` that has both titlesummary and arguments.

**Comment by TheCakeIsNaOH** [comment]
> but it'd be a bear to pull them out of the comments if I want to use the SavedArguments in something like InstChoco.

Hmm, yup.

I think the escaping should allow these to work as is, no need to put them in comments. Then it would be really easy to pull out the arguments if needed.

**Comment by bcurran3** [comment]
Cool. I'll give this a trial run soon. [System.Security.SecurityElement]::Escape() looks like a useful "new find." I don't know .net at all. I'm guessing this will also break PS Core compatibility, will try, but not worried about it.

**Comment by TheCakeIsNaOH** [comment]
> PS Core compatibility, will try,

Should work fine, no problems with pwsh 7 for me:
image

**Comment by bcurran3** [comment]
I just tested this and it is working for me. 

Honestly, I don't understand some of the escaping results that are showing for me; e.g.:
`arguments=" --cache-location=&quot;&apos;C:\Users\bcurran\AppData\Local\Temp\chocolatey&apos;&quot;"`
so I'm not sure if it's right or needs tweaking, either way it doesn't cause harm and moves the saved arguments request forward so I'm going to pull it in now.

I'll leave this open for the moment...

**Comment by TheCakeIsNaOH** [comment]
>  I don't understand some of the escaping results that are showing for me; e.g.:

Here is a list of the XML escape sequences:

```
"  = &quot;
'  = &apos;
<  = &lt;
>  = &gt;
&  = &amp;
```

So this:
`arguments=" --cache-location=&quot;&apos;C:\Users\bcurran\AppData\Local\Temp\chocolatey&apos;&quot;"`
Would translate to:
`arguments=" --cache-location="'C:\Users\bcurran\AppData\Local\Temp\chocolatey'""`

If you do a `get-content` and cast to xml, it should be translated.
Like `([xml](Get-Content packages.config)).packages.package.arguments`

Here is more info:
https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

**Comment by bcurran3** [comment]
Thanks.
I will search GH and reference that when needed!

I'm ready to push out a new version of the package with these updates. I can hold off if you want to optimize the creation routine or just push a new version afterwards. Thoughts? (i.e. When do you feel like doing it? :) )

**Comment by bcurran3** [comment]
UNRELATED: For some time now I've wanted to obtain your e-mail address for some more direct communication. In particular I'd love to know your first name. If you're not against it, you know how to e-mail me...

**Comment by TheCakeIsNaOH** [comment]
> I can hold off if you want to optimize the creation routine or just push a new version afterwards. Thoughts? (i.e. When do you feel like doing it? :) )

Let's get this out in the wild for a bit before optimizing the creation.

**Comment by bcurran3** [comment]
OK. I just pushed the new ver. It's a trusted package, so you won't have to moderate it. (I see you moderating a lot.)

Will see if there is any fallout....

Do me a favor, when it comes time, look at https://github.com/bcurran3/ChocolateyPackages/issues/230 and see if you could possible insert ([System.Security.SecurityElement]::Escape()) to escape the title and summary options as well. 

I'm still looking on feedback on moving the title, summary, and saved arguments to XML comments... but don't see a need... I can easily see how it is subjectively prettier or uglier... and a little angel on my shoulder keeps saying "If it's not broke, don't eff with it."

**Comment by TheCakeIsNaOH** [comment]
> but don't see a need

Neither do I, now that everything is (or should be) escaped properly.

If you want the individual lines to be shorter, the different items could be put on different lines, as the XML parser does not care about newlines (assuming it is following the spec AFAIK). So there should be no difference between these two formating option how they are read by the xml parser:

Option 1.
```
   <package 
       id="7zip.commandline" 
       title="[Deprecated] 7-Zip (Portable, CommandLine)" 
       summary="7-Zip is a file archiver with a high compression ratio." 
       arguments=" --cache-location=&quot;&apos;C:\Users\user\AppData\Local\Temp\chocolatey&apos;&quot;" 
   />
  <package 
       id="7zip.install"
       title="7-Zip (Install)" 
       summary="7-Zip is a file archiver with a high compression ratio." 
       arguments=" --cache-location=&quot;&apos;C:\Users\user\AppData\Local\Temp\chocolatey&apos;&quot;" 
   />
```

and Option 2.
```
<package id="7zip.commandline" title="[Deprecated] 7-Zip (Portable, CommandLine)" summary="7-Zip is a file archiver with a high compression ratio." arguments=" --cache-location=&quot;&apos;C:\Users\user\AppData\Local\Temp\chocolatey&apos;&quot;" />
<package id="7zip.install" title="7-Zip (Install)" summary="7-Zip is a file archiver with a high compression ratio." arguments=" --cache-location=&quot;&apos;C:\Users\user\AppData\Local\Temp\chocolatey&apos;&quot;" />
```

**Comment by TheCakeIsNaOH** [comment]
> Do me a favor, when it comes time, look at #230 and see if you could possible insert ([System.Security.SecurityElement]::Escape()) to escape the title and summary options as well.

I thought I already did in this PR? Both the title and summary should be escaped.

**Comment by bcurran3** [comment]
Hmmmmmmmmmmmm. Yeah, moving the elements to individual lines is another option I overlooked to make it more legible. Hmmmmmm. I like it! ...and I like it MORE!

I don't think you worked on escaping title and summary before. I just tested earlier today (with the choco-package-list-backup.ps1 downloaded from your repo) and both the title and summary info for notepadplusplus in a packages.config file will crap out a choco install. I figured the new super duper .net escaping technology could be inserted there pretty easy and fix that old bug which I blamed on choco.exe. It is choco.exe crapping out, but seems easy enough to get around it now.

EDIT: You're probably right. I ran choco install against a packages.config with the notepadplusplus info from the issue. I also ran choco install against all my saved packages running your updated choco-package-list-backup pulled from your repo and it had no problems. I did this a few times and am now clueless as to what choco-package-list-backup.config settings I had set now. I think I did run with title and summary saved, but not sure now. And I did not look directly at the code for related changes. This  might be all null and void. I really should look but will do later as I'm being called for family time...

**Comment by bcurran3** [comment]
Ahhhh yeah. I see it now!

**Pull request merged**
