### PR TITLE
AngryIP add AU script

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
Adds an AU script to angryip.

I use something very similar to this script for my personal version of the angryip package.

### CODE REVIEW

**Comment by TheCakeIsNaOH** [comment]
Also, I go the silent uninstall working, see: https://github.com/angryip/ipscan/pull/263

**Comment by bcurran3** [comment]
Cool, thanks!

**Review by bcurran3 — CHANGES_REQUESTED** [review]
The change to the install script will break it as that's not the correct file naming convention. There's no need to change how the file gets picked and put into the array, I don't do it this way purposely incase there are old versions that got stuck lying around.

I'll try the update script now.

**Review by bcurran3 — CHANGES_REQUESTED** [review]
I see the update script adds the _x32 to the filename. I prefer to keep the filename as is from the source to avoid any potential conspiracy theories that it got changed. (It's the times man, it's the times!)

Also the update script strips out the existing description and replaces it with the readme.md data which doesn't have the description in it. I'm assuming this is default AU behavior and a good reason for me not to use it until I update ALL 400+ readme.md's!!!!!!!!!!!

**Comment by TheCakeIsNaOH** [comment]
> I prefer to keep the filename as is from the source to avoid any potential conspiracy theories that it got changed.

Oh my. You speak from experience? 

> I prefer to keep the filename as is from the source to avoid any potential conspiracy theories that it got changed.

Fixed.

> Also the update script strips out the existing description and replaces it with the readme.md data which doesn't have the description in it.

Fixed. 

> I'm assuming this is default AU behavior

Yep. I disabled it with the `-NoReadme` switch.

**Comment by TheCakeIsNaOH** [comment]
I rebased on the current master after you force pushed master.

**Review by bcurran3 — CHANGES_REQUESTED** [review]
I can't accecpt the chocolateyinstall.ps1 change as there's no need, "  file          = "$toolsDir\ipscan-$ENV:ChocolateyPackageVersion-setup.exe"" is exactly the way I want it.

The update script I'll approve right away. I just ran it. No updates. I can only assume it works, if not - it doesn't effect anyone but me so no worries!

**Comment by TheCakeIsNaOH** [comment]
> I can't accecpt the chocolateyinstall.ps1 change as there's no need,

Done.

I'm personally not a fan of using `$ENV:ChocolateyPackageVersion` for the file name since it breaks if a package fix version is needed. 
It does work fine otherwise.

> I can only assume it works

You can always test an AU script by manually bumping the version number down to a previous version in the `.nuspec`, then doing
```
$au_nocheckchocoversion = $true
.\update.ps1
```

Or you could do
```
$au_force = $true
.\update.ps1
```
This one does not require a manual version down-bump. But this changes the version to one with package fix notation, so `1.0.0.020201120` or whatever, instead of using the actual `1.0.0.0` version.

**Comment by bcurran3** [comment]
I just did the latter, neat how AU appended with the date.

I really need to get around to using that as a base to create a generic update.ps1 that only needs a URL change for each package with a static download file. This has been my goal for a long time...soon as I have the time. Heading into the time of year now where I'll probably be putting in more Chocolatey packages work...

**Pull request merged**
