### PR TITLE
vmware-tools - v11.2.1.17243207 - ADDLOCAL=ALL parameter

### PR DESCRIPTION
**Pull request by virtualex-itv**
hey @bcurran3 - here is the latest release!  Please reassign me to this add add the labels as needed 👍 

---

Added the ADDLOCAL=ALL parameter to do a Complete Install of VMware Tools

`choco install vmware-tools` - performs a default "Typical" install

`choco install vmware-tools --params "/ALL"` - performs a "Complete" install

### CODE REVIEW

**Comment by virtualex-itv** [comment]
hey @bcurran3 - any update on this?

**Comment by bcurran3** [comment]
I'm just waiting for a new release; then I plan to test, merge, push.

**Comment by virtualex-itv** [comment]
@bcurran3 - this PR is of the latest release that dropped 3 weeks ago.  I closed the previous PR and resubmitted a new one since the previous PR was missed and you published the package without the new changes.  Current package available on chocolatey is ***11.2.0.16938113***, whereas this PR is for the latest ***11.2.1.17243207***
[Disqus Comment](http://disq.us/p/2dr9tut)

**Comment by gep13** [comment]
@bcurran3 can you please confirm if you are still interested in maintaining this package?  It seems like @virtualex-itv has an interest in helping within this package, and has added reminders the last couple of package versions when an update is available.

Would you like me to add @virtualex-itv as a co-maintainer of the package to help out?

**Comment by bcurran3** [comment]
@gep13 - everything is fine. 

image

**Comment by gep13** [comment]
@bcurran3 can you help me understand what this means?  Are you still in a position to maintain this package, or should I add @virtualex-itv as a co-maintainer on this package?

**Review by bcurran3 — APPROVED** [review]

**Pull request merged**
