### PR TITLE
New release Arq 7.12.3.0

### PR DESCRIPTION
**Pull request by basictheprogram**

### CODE REVIEW

**Comment by basictheprogram** [comment]
@bcurran3 Any issues with the PR?

Something you want me to change?

I would appreciate a merge and publish to the community feed so I don't have to push the release manually.

Thanks.

**Comment by bcurran3** [comment]
Hi Bob. Honestly I haven't had time to look at it. On top of that I thought I handed this package off to another maintainer. Would you like to become a (the) maintainer?

**Comment by basictheprogram** [comment]
Add me to the package maintainers.

Chocolatey username is basictheprogram.

https://community.chocolatey.org/profiles/basictheprogram


On Apr 26, 2022, at 6:54 PM, bcurran3 ***@***.******@***.***>> wrote:



Hi Bob. Honestly I haven't had time to look at it. On top of that I thought I handed this package off to another maintainer. Would you like to become a (the) maintainer?

--
Bob Tanner ***@***.******@***.***>>  | Phone : (952)943-8700
https://keybase.io/basictheprogram     | http://www.real-time.com
Key fingerprint = F785 DDFC CF94 7CE8 AA87 3A9D 3895 26F1 0DDB E378

**Comment by bcurran3** [comment]
Invite sent to become a maintainer

**Pull request closed without merging**
