### PR TITLE
(choco-package-list-backup) fix missing chocolatey nuspec

### LINKED ISSUE #233: (choco-package-list-backup) - Cannot find chocolatey.nuspec when SaveTitleSummary is enabled
When  `<SaveTitleSummary>true</SaveTitleSummary>` I get this:

```
choco-package-list-backup.ps1
choco-package-list-backup.ps1 v2020.04.06 - backup Chocolatey packages list locally and to the cloud
Copyleft 2017-2020 Bill Curran (bcurran3@yahoo.com) - free for personal and commercial use

Choco Package List Backup Summary:
Get-Content : Cannot find path 'C:\ProgramData\chocolatey\lib\chocolatey\chocolatey.nuspec' because it does not exist.
At C:\tools\BCURRAN3\choco-package-list-backup.ps1:117 char:23
+    [xml]$nuspecFile = Get-Content $nuspecXML
+                       ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...ocolatey.nuspec:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\ProgramData\chocolatey\lib\chocolatey\chocolatey.nuspec' because it does not exist.
At C:\tools\BCURRAN3\choco-package-list-backup.ps1:117 char:23
+    [xml]$nuspecFile = Get-Content $nuspecXML
+                       ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...ocolatey.nuspec:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
Fixes: #233

### CODE REVIEW

**Review by bcurran3 — COMMENTED** [review]
This is great. @TheCakeIsNaOH I'm so glad you're around to help me. Thank you.

I'm willing to pull this in but just want to ask your opinion first on two different options:

1 - Check for any missing nuspec as opposed to specifying Chocolatey and then run Read-NuspecFromNupkg. (Scenario would probably never happen, but...)
2 - Check for any missing nuspec and just skip reading it if not present. Just wondering how important the description for the Chocolatey package is.

Let me know your thoughts.

**Comment by TheCakeIsNaOH** [comment]
> 1 - Check for any missing nuspec as opposed to specifying Chocolatey and then run Read-NuspecFromNupkg. (Scenario would probably never happen, but...)

That would probably be appropriate. I'll go ahead and change to this.

> 2 - Check for any missing nuspec and just skip reading it if not present. Just wondering how important the description for the Chocolatey package is.

I considered this, but in this case, there would be no description returned, and I didn't want to screw up anything downstream in regards to not having anything returned.

**Comment by TheCakeIsNaOH** [comment]
@bcurran3 Any updates on getting this merged?

**Comment by bcurran3** [comment]
Apologies as I've purposely been avoiding/ignoring it until I have adequate time to focus on it. :)
I just finished up three concurrent projects for work and am now idle-ish... starting to get bored even. So I should jump on this sooner than later. 

In fact, I just got my Chocolatey creative juices flowing early this AM and did this update: 
https://chocolatey.org/packages/choco-upgrade-all-at/0.0.6-pre
If you already use choco-upgrade-all-at, test it for me. :)

**Comment by TheCakeIsNaOH** [comment]
> If you already use choco-upgrade-all-at, test it for me. :)

I'm the sort that likes to watch the updates to make sure things are working, so that's not really my thing. 

But I do like the new features, stuff like desktop icon management is sorely lacking in choco.

**Comment by bcurran3** [comment]
You can install it with /notask and just run manually :) I respect your opinion...

**Comment by bcurran3** [comment]
(Yeah, I should look at issues and PRs BEFORE I do updates.)

I just fixed this via https://github.com/bcurran3/ChocolateyPackages/commit/4d1dc01c305a88991ccf17fffa2f0f46eb0274d4 - Much simpler! :)

**Pull request closed without merging**
