### PR TITLE
variable and syntax cleanup

### PR DESCRIPTION
**Pull request by slycordinator**
* Added array variables for file types to be used in different phases
* Modified BinaryExtensions array to be on multiple lines for easier readability
* Changed code syntax to make order consistent

Also, it seems that vscode automatically changed some of the spacing/tabs in an attempt to place code consistent with the surrounding code in the same bracketed region and such. If you prefer not having that changed, I can try and revert that part.

### CODE REVIEW

**Comment by bcurran3** [comment]
@slycordinator Honestly, yes to your question! I looked through about a third of this (twice) and I only see spaces added. If you could submit without the "noise" it would be easier to read. THEN you could add the noise back in to make it pretty. :-)

**Comment by slycordinator** [comment]
I changed it to match the spacing used in the original as closely as I could. It reduced the number lines that are showing differences now.

Hope it helps.

**Comment by bcurran3** [comment]
Thanks. Now I can easily see what you did.

I noticed all the new arrays are defined after the if statements. Could you move them to the top with $BinaryExtensions so they're more easily found if/when necessary to modify them please?

**Comment by slycordinator** [comment]
Now, the variables are moved to the top.

Though it seems that the editor changed the spacing again.

After this PR gets incorporated, I'll see if I can make a separate PR to just make all of the spacing consistent between tabs vs spaces.

**Comment by bcurran3** [comment]
Let's get this pulled in... and if you want to clean up spacing in another PR, sure ting.

**Pull request merged**
