### PR TITLE
Updated sha256 checksum

### PR DESCRIPTION
**Pull request by basictheprogram**
Updated sha256 checksum
Added .gitignore

### CODE REVIEW

**Comment by bcurran3** [comment]
Hi.
Why the .gitignore? - the nupkg isn't in GH.
nuspec needs to be updated w/version for this to be 100%

**Comment by basictheprogram** [comment]
Without the .gitignore `git status` shows the .nupkg as untracked. And I tend to do a `git add --all` as I work.

**Review by bcurran3 — APPROVED** [review]

**Comment by bcurran3** [comment]
pulling in and pushing package update

**Comment by bcurran3** [comment]
I think we get the same result just done in different ways by each of us.

I add *.nuspec to the local git ignore file. I also do a "git add *" before adding commits. I do not get any untracked files error when doing a "git status." 

If I understand all this correctly (and believe me when it comes to git there's a LOT I don't know), I'd suggest adding *.nuspec to your local git config ignore file as you only need to do it once versus adding a .gitignore to all of your package folders. I'm lazy, is suits me. :)

**Pull request merged**
